imageTag: supermongol/doe-demo-ui
codeScan:
  enabled: true
  coverageFile: coverage/cobertura-coverage.xml
  #coverageFile: ""
imageScan:
  enabled: false
imageBuild:
  enabled: false
imagePublish:
  enabled: false
deploy:
  enabled: false
  gatecheckConfigFilename: .gatecheck.yml

