steps:
  # Build the image using Portage
  - name: 'ghcr.io/easy-up/portage:v0.0.1-rc.19'
    env:
     - "PORTAGE_IMAGE_PUBLISH_ENABLED=0"
    args: [
      'run', 'all', '--tag', '${_IMAGE_NAME}'
    ]

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}']

  # Deploy the application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_IMAGE_NAME}',
      '--region', '${_REGION}',
      '--project', '${_PROJECT_ID}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

# Define default variables (will be overridden by trigger substitutions)
substitutions:
  _REGION: "us-west1"  # Default region
  _PROJECT_ID: "holomua-demo"  # Default project
  _SERVICE_NAME: "demo-ui"  # Will be overridden by trigger (e.g., demo-ui-dev)
  _IMAGE_NAME: "us-west1-docker.pkg.dev/shared-resources-gcp/shared-container-registry/demo-ui"  # Will be overridden by trigger

options:
  logging: CLOUD_LOGGING_ONLY
